@url_dev=http://localhost:8000

@apiKey=411d465245c48ec89a965a7f951699d2a9497ee74971539ea621f112fb90c56c69fecbdcd0897bb7585a128292c0dd0704371d2299baec86b925b6d032dce518

@clientId=66d21aa17643f907e7cf1738

@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQyMWFhMTc2NDNmOTA3ZTdjZjE3MzgiLCJlbWFpbCI6ImJsdWVAZ21haWwuY29tIiwiaWF0IjoxNzI1NTc5MzY4LCJleHAiOjE3MjU3NTIxNjh9.2ggVsyEfVsHjgdbPZdPImnnI1Yok6hkQy-TmTWKfb7I

@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQyMWFhMTc2NDNmOTA3ZTdjZjE3MzgiLCJlbWFpbCI6ImJsdWVAZ21haWwuY29tIiwiaWF0IjoxNzI1NTc5MzY4LCJleHAiOjE3MjYxODQxNjh9.Czr6g5uoHGh5lAyEYrwHMIyBg0rGQW4FtnkCjZMBEZU


### Create API Key
POST {{url_dev}}/v1/api/key
Content-Type: application/json
x-api-key: {{apiKey}}


### Sign Up
POST {{url_dev}}/v1/api/shop/signUp
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "name": "diepsang",
    "email": "blue@gmail.com",
    "password": "123"
}


### Login
POST {{url_dev}}/v1/api/shop/login
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "email": "blue@gmail.com",
    "password": "123"
}


### Handle Refresh Token
POST {{url_dev}}/v1/api/shop/handleRefreshToken
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
x-rtoken-id: {{refreshToken}}

{
    "refreshToken": "{{refreshToken}}"
}


### Logout
POST {{url_dev}}/v1/api/shop/logout
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Create new Product
POST {{url_dev}}/v1/api/product
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "product_name": "IPhone 19 1000GB",
    "product_desc": "don dau cong nghe",
    "product_thumb": "link",
    "product_price": 999,
    "product_quantity": 999,
    "product_type": "Electronic",
    "product_attributes": {
        "manufacturer": "APSBOF",
        "model": "Corei999",
        "color": "Blue"
    }
}


### Get Draft Products in Shop
GET {{url_dev}}/v1/api/product/drafts?page=1
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Get Publised Products in Shop
GET {{url_dev}}/v1/api/product/published?page=1
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Publish Products for Shop
PUT {{url_dev}}/v1/api/product/publish/66d21b6b7643f907e7cf1756
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### UnPublish Products for Shop
PUT {{url_dev}}/v1/api/product/unpublish/66cbc908935dbc5d5a2fbcae
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Get list searhc Products for Shop
GET {{url_dev}}/v1/api/product/search/bang
Content-Type: application/json
x-api-key: {{apiKey}}


### Get list Products
GET {{url_dev}}/v1/api/product
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Get detail Products
GET {{url_dev}}/v1/api/product/66d21b6b7643f907e7cf1756
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Update Proudct
PATCH  {{url_dev}}/v1/api/product/66ccd29452e3f5979d31b535
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "product_type": "Clothing",
    "product_price": 199
}

### Create Discount
POST {{url_dev}}/v1/api/discount
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "code": "AO-THUN-123",
    "name": "Ao thun 10",
    "desc": "Giam gia ao thung",
    "type": "percentage",
    "value": 10,
    "max_value": 30000,
    "min_order_value": 2000,
    "shopId": "66d21aa17643f907e7cf1738",
    "max_uses": 100,
    "uses_count": 0,
    "users_used": [],
    "max_uses_per_user": 1,
    "is_active": true,
    "applies_to": "specific",
    "product_ids": ["66d21b207643f907e7cf174e", "66d21b027643f907e7cf1746"],
    "start_date": "2024-08-30 09:00:00",
    "end_date": "2024-09-02 09:00:00"
}


### Get Products of Discount
GET {{url_dev}}/v1/api/discount/product?code=SHOP-123&limit=50&page=1
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Get Products in Shop
GET {{url_dev}}/v1/api/discount/66ccd23252e3f5979d31b52c?limit=50&page=1
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Get Discount Amount
POST {{url_dev}}/v1/api/discount/amount
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "code": "AO-THUN-123",
    "shopId": "66d21aa17643f907e7cf1738",
    "userId": "66d21aa17643f907e7cf1738",
    "products": [
        {
            "id": "66d21b207643f907e7cf174e",
            "quantity": 20,
            "price": 230
        }
    ]
}


### Add a Product to Cart
POST {{url_dev}}/v1/api/cart
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "productId": "66d21b6b7643f907e7cf1756",
    "quantity": 2
}


### Get Cart
GET {{url_dev}}/v1/api/cart
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Delete a Product from Cart
DELETE {{url_dev}}/v1/api/cart/:id
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Update Cart
POST {{url_dev}}/v1/api/cart/update
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "productId": "66ccd29452e3f5979d31b535",
    "quantity": "6"
}


### Review Checkout
POST {{url_dev}}/v1/api/checkout/review
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "cartId": "66d21fd0a4947466ca7bbf44",
    "order": [
        {
            "shopId": "66d21aa17643f907e7cf1738",
            "discountCodes": ["AO-THUN-123"],
            "products": [
                {
                    "id": "66d21b207643f907e7cf174e",
                    "quantity": 8
                },
                {
                    "id": "66d21b027643f907e7cf1746",
                    "quantity": 3
                },
                {
                    "id": "66d21b6b7643f907e7cf1756",
                    "quantity": 2
                }
            ]
        }
    ]
}


### Order
POST {{url_dev}}/v1/api/checkout/order
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "cartId": "66d21fd0a4947466ca7bbf44",
    "order": [
        {
            "shopId": "66d21aa17643f907e7cf1738",
            "discountCodes": ["AO-THUN-123"],
            "products": [
                {
                    "id": "66d21b207643f907e7cf174e",
                    "quantity": 8
                },
                {
                    "id": "66d21b027643f907e7cf1746",
                    "quantity": 3
                },
                {
                    "id": "66d21b6b7643f907e7cf1756",
                    "quantity": 2
                }
            ]
        }
    ],
    "userAddress": "",
    "userPayment": ""
}


### Create Comment
POST {{url_dev}}/v1/api/comment
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

# {
#     "userId": "12345",
#     "productId": "66d21b207643f907e7cf174e",
#     "content": "giao hang nhanh"
# }

{
    "userId": "8273",
    "productId": "66d21b207643f907e7cf174e",
    "content": "shop cam on",
    "parentCommentId": "66da58b5de7167af44d10b15"
}

# {
#     "userId": "777",
#     "productId": "66d21b207643f907e7cf174e",
#     "content": "tam on",
#     "parentCommentId": "66da587dde7167af44d10b03"
# }


### Get Comments with Product
GET {{url_dev}}/v1/api/comment/product/66d21b207643f907e7cf174e
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Delete Comment
DELETE  {{url_dev}}/v1/api/comment/66da588cde7167af44d10b08
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}