@url_dev=http://localhost:8000

@apiKey=887ee8823896d9dbadafc619654e5dafc424550b1b960af3c878de946527fed63381698878c6f05766ee318405d53ebd7100e6929975a8a2c23e1d19eb045331

@clientId=66ccd23252e3f5979d31b52c

@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNjZDIzMjUyZTNmNTk3OWQzMWI1MmMiLCJlbWFpbCI6ImJsdWVAZ21haWwuY29tIiwiaWF0IjoxNzI0Njk5MTg2LCJleHAiOjE3MjQ4NzE5ODZ9.hUPZTMH-mi1q3DGdH0yN5hwndTXL3oojEjkQlfb2ooc

@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNjZDIzMjUyZTNmNTk3OWQzMWI1MmMiLCJlbWFpbCI6ImJsdWVAZ21haWwuY29tIiwiaWF0IjoxNzI0Njk5MTg2LCJleHAiOjE3MjUzMDM5ODZ9.1BlQ5JfBrTMG8o9jxOQth6b_FWWz7s4SqzqFpSwJBcs


### Sign Up
POST {{url_dev}}/v1/api/shop/signUp
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "name": "diepsang",
    "email": "blue@gmail.com",
    "password": "123"
}


### Login
POST {{url_dev}}/v1/api/shop/login
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "email": "blue05@gmail.com",
    "password": "123"
}


### Handle Refresh Token
POST {{url_dev}}/v1/api/shop/handleRefreshToken
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
x-rtoken-id: {{refreshToken}}

{
    "refreshToken": "{{refreshToken}}"
}


### Logout
POST {{url_dev}}/v1/api/shop/logout
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Create new Product
POST {{url_dev}}/v1/api/product
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "product_name": "ao thun tron",
    "product_desc": "thoang mat",
    "product_thumb": "link",
    "product_price": 187,
    "product_quantity": 200,
    "product_type": "Clothing",
    "product_attributes": {
        "brand": "blue",
        "size": "XL",
        "material": "cotton"
    }
}


### Get Draft Products in Shop
GET {{url_dev}}/v1/api/product/drafts?page=1
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Get Publised Products in Shop
GET {{url_dev}}/v1/api/product/published?page=1
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Publish Products for Shop
PUT {{url_dev}}/v1/api/product/publish/66ccd2dc52e3f5979d31b543
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### UnPublish Products for Shop
PUT {{url_dev}}/v1/api/product/unpublish/66cbc908935dbc5d5a2fbcae
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Get list searhc Products for Shop
GET {{url_dev}}/v1/api/product/search/ao thun
Content-Type: application/json
x-api-key: {{apiKey}}


### Get list Products
GET {{url_dev}}/v1/api/product
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Get detail Products
GET {{url_dev}}/v1/api/product/66ccd29452e3f5979d31b535
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Update Proudct
PATCH  {{url_dev}}/v1/api/product/66ccd29452e3f5979d31b535
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "product_type": "Clothing",
    "product_price": 199
}

### Create Discount
POST {{url_dev}}/v1/api/discount
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "code": "SHOP-12344",
    "name": "Test",
    "desc": "Test create discount",
    "type": "percentage",
    "value": 30000,
    "max_value": 30000,
    "min_order_value": 200000,
    "shopId": "66ccd23252e3f5979d31b52c",
    "max_uses": 100,
    "uses_count": 0,
    "users_used": [],
    "max_uses_per_user": 1,
    "is_active": true,
    "applies_to": "specific",
    "product_ids": ["66ccd29452e3f5979d31b535", "66ccd2dc52e3f5979d31b543"],
    "start_date": "2024-08-27 09:00:00",
    "end_date": "2024-08-30 09:00:00"
}


### Get Products of Discount
GET {{url_dev}}/v1/api/discount/product?code=SHOP-123&limit=50&page=1
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Get Products in Shop
GET {{url_dev}}/v1/api/discount/66ccd23252e3f5979d31b52c?limit=50&page=1
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Get Discount Amount
POST {{url_dev}}/v1/api/discount/amount
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "code": "SHOP-123",
    "shopId": "66ccd23252e3f5979d31b52c",
    "userId": "66ccd23252e3f5979d31b52c",
    "products": [
        {
            "id": "66ccd29452e3f5979d31b535",
            "quantity": 20,
            "price": 1200
        }
    ]
}