@url_dev=http://localhost:8000

@apiKey=529ba547a4b136661f869a7f46fdd470f77d21e723ed08ad46e63013e34f07fac33e0e86751973e2c1abe04d5a3e132857b022e5385c205ad24951e0bfbbf513

@clientId=66c9b818ed301b3355940c97

@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmM5YjgxOGVkMzAxYjMzNTU5NDBjOTciLCJlbWFpbCI6ImJsdWUwNUBnbWFpbC5jb20iLCJpYXQiOjE3MjQ2MzE1NjgsImV4cCI6MTcyNDgwNDM2OH0.ty45pad6PquojnnbScp7DgfO3VeHeaHOyxzAi51t72g

@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmM5YjgxOGVkMzAxYjMzNTU5NDBjOTciLCJlbWFpbCI6ImJsdWUwNUBnbWFpbC5jb20iLCJpYXQiOjE3MjQ2MzE1NjgsImV4cCI6MTcyNTIzNjM2OH0.EAG72VNnwK6CfJJZ7DNSSB9r-OI86JQ-zT8c6CBsO8s


### Sign Up
POST {{url_dev}}/v1/api/shop/signUp
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "name": "diepsang",
    "email": "bluefffd@gmail.com",
    "password": "123"
}


### Login
POST {{url_dev}}/v1/api/shop/login
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "email": "blue05@gmail.com",
    "password": "123"
}


### Handle Refresh Token
POST {{url_dev}}/v1/api/shop/handleRefreshToken
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
x-rtoken-id: {{refreshToken}}

{
    "refreshToken": "{{refreshToken}}"
}


### Logout
POST {{url_dev}}/v1/api/shop/logout
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Create new Product
POST {{url_dev}}/v1/api/product
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "product_name": "ao thun tron 100% cotton",
    "product_desc": "New Product",
    "product_thumb": "Thumb-Link-New-Product",
    "product_price": 1000,
    "product_quantity": 13,
    "product_type": "Clothing",
    "product_attributes": {
        "brand": "New",
        "size": "New",
        "material": "New"
    }
}


### Get Draft Products in Shop
GET {{url_dev}}/v1/api/product/drafts?page=1
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Get Publised Products in Shop
GET {{url_dev}}/v1/api/product/published?page=1
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Publish Products for Shop
PUT {{url_dev}}/v1/api/product/publish/66cbc908935dbc5d5a2fbcae
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### UnPublish Products for Shop
PUT {{url_dev}}/v1/api/product/unpublish/66cbc908935dbc5d5a2fbcae
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Get list searhc Products for Shop
GET {{url_dev}}/v1/api/product/search/ao thun
Content-Type: application/json
x-api-key: {{apiKey}}


### Get list Products
GET {{url_dev}}/v1/api/product
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Get detail Products
GET {{url_dev}}/v1/api/product/66cbc908935dbc5d5a2fbcae
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}


### Update Proudct
PATCH  {{url_dev}}/v1/api/product/66cbc908935dbc5d5a2fbcae
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
authorization: {{accessToken}}

{
    "product_type": "Clothing",
    "product_attributes": {
        "brand": "blue"
    },
    "product_name": "ao thun tron cao cap 100% cotton",
    "product_quantity": 99
}

# {
#     "product_type": "Clothing",
#     "product_attributes": {
#         "brand": "gem",
#         "size": "XL",
#         "material": "Cotton"
#     },
#     "product_name": "ao thun tron cao cap 100% cotton",
#     "product_desc": "chat lieu thoang mat",
#     "product_quantity": 99
# }





